name: Test and lint cardfunctions.py on edit.

on:
  push:
    branches: [ master ]
    paths:
      - "cardfunctions.py"
  pull_request:
    branches: [ master ]
    paths:
      - "cardfunctions.py"

jobs:
  build-lint:
    name: Build, Lint and Artifact
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Lint application
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m flake8 cardfunctions.py
        
    - name: Upload the built cardfunctions package.
      uses: actions/upload-artifact@v2
      with:
        name: cardfunctions (Built)
        path: "cardfunctions.py"
        
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    needs: build-lint
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
